# Generated by Django 4.1.3 on 2022-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('number_of_shows', models.PositiveIntegerField()),
            ],
        ),
    ]
