# Generated by Django 4.1.3 on 2022-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('number_of_shows', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieModel',
        ),
    ]
