# Generated by Django 4.1.3 on 2022-11-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movies_delete_moviemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
